title               : Zhaak
description         : >-                               # >- signifie ignorer les nouvelles lignes jusqu'Ã  ce que "url:"
                      Developer and designer for Moozie.

url                 : "http://www.zhaak.fr/"
repository          : Zhaak63/Zhaak.fr 

email: contact.zhaak@gmail.com
github_user: Zhaak63
instagram: hugoprch
twitter: ZhaakFX
dribbble: Zhaak


exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock